@extends('layouts.app')

@section('content')
<div class="row align-items-center py-5 animated-fade">
    <div class="col-lg-6 mb-5 mb-lg-0">
        <span class="badge badge-scope1 px-3 py-2 rounded-pill mb-3 text-uppercase fw-bold" style="letter-spacing: 1px; font-size: 0.75rem;">
            <i class="fa-solid fa-earth-americas me-1 animate-pulse"></i> Carbon Accounting Platform
        </span>
        <h1 class="display-4 fw-extrabold text-white mb-4" style="line-height: 1.15; letter-spacing: -1px;">
            Measure and Manage Your <span style="background: linear-gradient(135deg, #10b981 0%, #3b82f6 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Carbon Footprint</span>
        </h1>
        <p class="lead text-secondary mb-5" style="font-size: 1.15rem; line-height: 1.6;">
            JejakKarbonmu is a high-performance carbon accounting application designed to track, calculate, and log Scope 1, 2, and 3 emissions. Compliant with international standard frameworks like the GHG Protocol and IPCC.
        </p>
        <div class="d-flex flex-wrap gap-3">
            <a href="{{ route('records.create') }}" class="btn-premium py-3 px-4 fs-6">
                <i class="fa-solid fa-play me-2"></i>Start Calculation
            </a>
            <a href="{{ route('records.history') }}" class="btn-premium-outline py-3 px-4 fs-6">
                <i class="fa-solid fa-list-ul me-2"></i>View History
            </a>
        </div>
    </div>
    
    <div class="col-lg-6 text-center">
        <!-- Visual Glass Card summarizing calculations -->
        <div class="glass-card p-5 text-start border-scope1 position-relative overflow-hidden" style="background: linear-gradient(145deg, #1e293b 0%, #0f172a 100%); border-radius: 24px;">
            <div class="position-absolute top-0 end-0 p-4 opacity-10">
                <i class="fa-solid fa-leaf text-success" style="font-size: 10rem;"></i>
            </div>
            
            <h3 class="h4 text-white mb-4"><i class="fa-solid fa-circle-nodes text-success me-2"></i>GHG Protocol Standard</h3>
            <div class="mb-4">
                <p class="text-secondary mb-1" style="font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.5px;">Activity Multiplier Formula</p>
                <div class="bg-dark p-3 rounded-3 font-monospace border border-secondary border-opacity-25 text-success d-flex justify-content-between align-items-center">
                    <span>Emission = Activity Data &times; EF</span>
                    <i class="fa-solid fa-equals text-muted"></i>
                </div>
            </div>
            
            <div class="d-flex justify-content-between align-items-center border-top border-secondary border-opacity-25 pt-4">
                <div>
                    <h5 class="text-white mb-1">Tableau Connected</h5>
                    <p class="text-secondary mb-0" style="font-size: 0.85rem;">Ready to pull and render KPI dashboards.</p>
                </div>
                <div class="d-flex gap-2">
                    <span class="badge badge-scope1 py-2 px-3 rounded-3"><i class="fa-solid fa-database"></i> SQL</span>
                    <span class="badge badge-scope2 py-2 px-3 rounded-3"><i class="fa-solid fa-chart-line"></i> BI</span>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="border-secondary opacity-25 my-5">

<!-- Scopes Explanation Section -->
<div class="py-4 animated-fade" style="animation-delay: 0.2s;">
    <div class="text-center mb-5">
        <h2 class="h1 fw-bold text-white mb-3">Understanding Emission Scopes</h2>
        <p class="text-secondary mx-auto" style="max-width: 600px;">To accurately assess your organization's carbon impact, greenhouse gas emissions are categorized into three distinct "Scopes" defined by the Greenhouse Gas Protocol.</p>
    </div>
    
    <div class="row g-4">
        <!-- Scope 1 Card -->
        <div class="col-md-4">
            <div class="glass-card h-100 p-4 border-scope1">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="p-3 rounded-3 badge-scope1">
                        <i class="fa-solid fa-fire-burner fs-3"></i>
                    </div>
                    <span class="badge badge-scope1 py-2 px-3 rounded-pill fw-bold">Scope 1</span>
                </div>
                <h3 class="h4 text-white mb-3">Direct Emissions</h3>
                <p class="text-secondary mb-0" style="font-size: 0.95rem; line-height: 1.6;">
                    Emissions directly generated by your organization's owned or controlled sources. Examples include fuel combustion in company boilers, furnaces, and vehicles, as well as fugitive chemical/refrigerant releases.
                </p>
                <div class="mt-4 pt-3 border-top border-secondary border-opacity-25">
                    <span class="text-secondary fw-semibold" style="font-size: 0.85rem;">Categories Include:</span>
                    <div class="d-flex flex-wrap gap-2 mt-2">
                        <span class="badge bg-secondary bg-opacity-25 text-white">Diesel</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Petrol</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">LPG</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Natural Gas</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Refrigerant</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Scope 2 Card -->
        <div class="col-md-4">
            <div class="glass-card h-100 p-4 border-scope2">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="p-3 rounded-3 badge-scope2">
                        <i class="fa-solid fa-bolt fs-3"></i>
                    </div>
                    <span class="badge badge-scope2 py-2 px-3 rounded-pill fw-bold">Scope 2</span>
                </div>
                <h3 class="h4 text-white mb-3">Purchased Energy</h3>
                <p class="text-secondary mb-0" style="font-size: 0.95rem; line-height: 1.6;">
                    Indirect emissions associated with the generation of electricity, steam, heating, or cooling purchased and consumed by your organization. These emissions physically occur at the power plant or facility where the utility is generated.
                </p>
                <div class="mt-4 pt-3 border-top border-secondary border-opacity-25">
                    <span class="text-secondary fw-semibold" style="font-size: 0.85rem;">Categories Include:</span>
                    <div class="d-flex flex-wrap gap-2 mt-2">
                        <span class="badge bg-secondary bg-opacity-25 text-white">Purchased Electricity</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Purchased Steam</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Scope 3 Card -->
        <div class="col-md-4">
            <div class="glass-card h-100 p-4 border-scope3">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="p-3 rounded-3 badge-scope3">
                        <i class="fa-solid fa-briefcase fs-3"></i>
                    </div>
                    <span class="badge badge-scope3 py-2 px-3 rounded-pill fw-bold">Scope 3</span>
                </div>
                <h3 class="h4 text-white mb-3">Indirect Value Chain</h3>
                <p class="text-secondary mb-0" style="font-size: 0.95rem; line-height: 1.6;">
                    All other indirect emissions that occur in your organization's value chain, including both upstream and downstream operations. This is highly customizable and encompasses business travel, employee commuting, waste management, and purchased goods.
                </p>
                <div class="mt-4 pt-3 border-top border-secondary border-opacity-25">
                    <span class="text-secondary fw-semibold" style="font-size: 0.85rem;">Categories Include:</span>
                    <div class="d-flex flex-wrap gap-2 mt-2">
                        <span class="badge bg-secondary bg-opacity-25 text-white">Business Travel</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Commuting</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Waste</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Water Supply</span>
                        <span class="badge bg-secondary bg-opacity-25 text-white">Purchased Goods</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bottom Call to Action -->
<div class="py-5 text-center mt-4 animated-fade" style="animation-delay: 0.3s;">
    <div class="glass-card p-5 border border-secondary border-opacity-25 rounded-4 d-inline-block w-100" style="background: linear-gradient(135deg, #1e293b 0%, #0b1329 100%);">
        <h3 class="h2 text-white mb-3">Ready to Calculate Your Carbon Footprint?</h3>
        <p class="text-secondary mx-auto mb-4" style="max-width: 500px;">Input your energy consumption and active categories to generate calculation details and save them to the historical database.</p>
        <a href="{{ route('records.create') }}" class="btn-premium btn-lg px-5">
            <i class="fa-solid fa-calculator me-2"></i>Open Calculator
        </a>
    </div>
</div>
@endsection
